import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from '@phosphor-icons/react';
import {
  ArrowDown,
  ArrowsClockwise,
  ArrowsLeftRight,
  ArrowsSplit,
  ArrowSquareOut,
  ArrowUp,
  Bell,
  Broadcast,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChartLineUp,
  Check,
  Code,
  Coin,
  Copy,
  CreditCard,
  Cube,
  CurrencyDollar,
  DownloadSimple,
  Envelope,
  Eye,
  Flask,
  Folder,
  FunnelSimple,
  GearSix,
  Image,
  Key,
  Lightning,
  LinkSimple,
  List,
  MagnifyingGlass,
  Moon,
  PaperPlaneTilt,
  Play,
  Plugs,
  PlugsConnected,
  Plus,
  Pulse,
  Calculator,
  BookOpen,
  Receipt,
  Rocket,
  ShieldCheck,
  SquaresFour,
  Sun,
  Target,
  Timer,
  Trash,
  TreeStructure,
  Users,
  UsersThree,
  WarningCircle,
  X,
} from '@phosphor-icons/react';

/**
 * The icon set is Phosphor, unmodified. Nothing here is drawn by hand; the
 * table below aliases the vocabulary this app already speaks ("Tx", "Defi",
 * "Webhook") onto Phosphor's names, so every existing `<Icon.X />` call site
 * is untouched and there is no icon design to maintain. To change a picture,
 * change one line.
 */

export type IconProps = PhosphorIconProps & { size?: number };

/**
 * Phosphor sizes to `1em`, which would take icons from whatever text they sit
 * beside, in 12px mono chrome that silently shrinks them. This system sizes
 * icons explicitly, so 16px stays the default, and `regular` is the weight
 * closest to the hairline everything else is drawn with.
 */
function icon(Glyph: PhosphorIcon) {
  return ({ size = 16, weight = 'regular', ...rest }: IconProps) => (
    <Glyph size={size} weight={weight} {...rest} />
  );
}

export const Icon = {
  Grid: icon(SquaresFour),
  Chart: icon(ChartBar),
  Image: icon(Image),
  Coin: icon(Coin),
  Tx: icon(ArrowsLeftRight),
  Defi: icon(ChartLineUp),
  Social: icon(UsersThree),
  Send: icon(PaperPlaneTilt),
  Prediction: icon(Target),
  Stablecoin: icon(CurrencyDollar),
  Code: icon(Code),
  Webhook: icon(Broadcast),
  Beaker: icon(Flask),
  Folder: icon(Folder),
  Users: icon(Users),
  Card: icon(CreditCard),
  Menu: icon(List),
  Search: icon(MagnifyingGlass),
  Plus: icon(Plus),
  Chevron: icon(CaretRight),
  ChevronLeft: icon(CaretLeft),
  ChevronDown: icon(CaretDown),
  Sun: icon(Sun),
  Moon: icon(Moon),
  Bell: icon(Bell),
  Copy: icon(Copy),
  Eye: icon(Eye),
  Check: icon(Check),
  X: icon(X),
  Key: icon(Key),
  Play: icon(Play),
  Trash: icon(Trash),
  Refresh: icon(ArrowsClockwise),
  External: icon(ArrowSquareOut),
  Mail: icon(Envelope),
  Download: icon(DownloadSimple),
  Settings: icon(GearSix),
  Filter: icon(FunnelSimple),
  Link: icon(LinkSimple),
  Cube: icon(Cube),
  Nodes: icon(TreeStructure),
  Lightning: icon(Lightning),
  Rocket: icon(Rocket),
  Book: icon(BookOpen),
  Calculator: icon(Calculator),
  Up: icon(ArrowUp),
  Down: icon(ArrowDown),
  Route: icon(ArrowsSplit),
  Socket: icon(PlugsConnected),
  Unplugged: icon(Plugs),
  Shield: icon(ShieldCheck),
  Alert: icon(WarningCircle),
  Pulse: icon(Pulse),
  Timer: icon(Timer),
  Receipt: icon(Receipt),
};
